name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-testing version to install (default: 3.12.0)"
    required: false
    default: '3.14.0'
  yamllint_version:
    description: "The yamllint version to install (default: 1.27.1)"
    required: false
    default: '1.33.0'
  yamale_version:
    description: "The yamale version to install (default: 6.0.0)"
    required: false
    default: '6.0.0'
runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
    - run: |
        cd $GITHUB_ACTION_PATH \
        && ./ct.sh \
            --version ${{ inputs.version }} \
            --yamllint-version ${{ inputs.yamllint_version }} \
            --yamale-version ${{ inputs.yamale_version }}
      shell: bash
